(async function(){
 const host=document.getElementById('journal-section');if(!host)return;
 const J=JournalEngine,P=PortfolioEngine,labels={QQQ:'주식',GOLD:'금',BTC:'비트코인',CASH:'현금·단기채'},money=n=>n.toLocaleString('ko-KR')+'원',esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const today=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Seoul'}).format(new Date());let draft=null,locked=false;
 host.innerHTML=`<h2>실제 매매일지</h2><p>위에 입력한 보유액을 <strong>거래 직전 평가액</strong>으로 사용합니다. 실제 주문을 실행하지 않으며 저장 후에도 보유액 입력은 자동 변경하지 않습니다.</p><form id="journal-form"><label>거래일 <input id="journal-date" type="date" value="${today}" max="${today}" required></label><label>이번 기록에 포함할 신규 입금 (원) <input id="journal-deposit" type="number" value="0" min="0" step="1" required></label><div class="table-wrap"><table><thead><tr><th>자산</th><th>실제 매수 원</th><th>실제 매도 원</th></tr></thead><tbody>${['QQQ','GOLD','BTC'].map(a=>`<tr><th>${labels[a]}</th><td><input aria-label="${labels[a]} 실제 매수금액" id="journal-buy-${a}" type="number" min="0" step="1" value="0" required></td><td><input aria-label="${labels[a]} 실제 매도금액" id="journal-sell-${a}" type="number" min="0" step="1" value="0" required></td></tr>`).join('')}</tbody></table></div><label>그때 왜 그렇게 했나요? <select id="journal-reason" required><option value="">이유 선택</option>${J.reasons.map(r=>`<option>${r}</option>`).join('')}</select></label><label>메모 <textarea id="journal-memo" maxlength="4000"></textarea></label><button class="secondary" type="submit">기록 미리보기</button><div id="journal-preview"></div><button class="primary" id="journal-confirm" type="button" hidden>당시 Snapshot과 매매일지 저장</button></form><p id="journal-status" role="status"></p><h3>저장한 판단과 Portfolio Impact</h3><p>결정 직후 보유구성을 그대로 유지한 영향을 추적합니다. 이후 매매·추가 입금이 포함된 실제 계좌 수익률과 다릅니다. 가격 미연결 기간은 대기 상태입니다.</p><div id="journal-list"></div>`;
 const get=id=>document.getElementById(id),status=s=>get('journal-status').textContent=s;
 function invalidate(){draft=null;get('journal-confirm').hidden=true;get('journal-preview').textContent='변경된 입력으로 다시 미리보기해 주세요.';}
 get('journal-form').oninput=invalidate;get('portfolio-form').addEventListener('input',invalidate);
 async function list(){const entries=await AllocationStore.list('journals');const rendered=[];
   for(const e of entries.sort((a,b)=>b.tradeDate.localeCompare(a.tradeDate))){let performance=e.futurePerformance;try{const fresh=await J.impact(e,AllocationData.get(),today);for(const [key,v] of Object.entries(performance||{}))if(v.status==='ready'&&fresh[key]?.status!=='ready')fresh[key]=v;performance=fresh;if(JSON.stringify(performance)!==JSON.stringify(e.futurePerformance))await AllocationStore.updatePerformance('journals',e.id,performance);}catch{status('일지는 불러왔지만 일부 가격 데이터 갱신에 실패했습니다.');}
     rendered.push(`<details><summary>${esc(e.tradeDate)} · ${esc(e.reasonCategory)} · 거래 후 ${money(P.value(e.portfolioAfter))}</summary><p>${esc(e.reasonMemo)}</p><p>Score 기준일 ${esc(e.scoreObservationDate||'미확보')} · 모델 ${esc(e.modelVersion)}</p><p>${P.ASSETS.map(a=>`${labels[a]} Score ${e.assetScoresAtDecision[a]??'—'} · 가격 ${e.pricesAtDecision[a]??'미확보'}`).join(' / ')}</p><div class="table-wrap"><table><thead><tr><th>자산</th><th>거래 전</th><th>거래 후</th></tr></thead><tbody>${P.ASSETS.map(a=>`<tr><th>${labels[a]}</th><td>${money(e.portfolioBefore[a])}</td><td>${money(e.portfolioAfter[a])}</td></tr>`).join('')}</tbody></table></div><ul>${Object.entries(performance||{}).map(([k,r])=>`<li>${k}: ${r.status==='ready'?`${(r.portfolioReturn*100).toFixed(2)}% · 그대로 유지 ${(r.counterfactualReturn*100).toFixed(2)}% · 차이 ${r.impactPercentagePoints.toFixed(2)}%p · MDD ${r.mdd===null?'자료 부족':(r.mdd*100).toFixed(2)+'%'} (${esc(r.valuationDate)})`:esc(r.reason||'대기')}</li>`).join('')}</ul></details>`);
   }get('journal-list').innerHTML=rendered.join('')||'<p>아직 저장한 일지가 없습니다.</p>';
 }
 get('journal-form').onsubmit=async event=>{event.preventDefault();if(locked)return;locked=true;draft=null;get('journal-confirm').hidden=true;try{
   const read=id=>{if(!get(id).value.trim())throw Error('금액을 모두 입력하세요. 미보유 자산은 0을 입력하세요.');return Number(get(id).value);};
   const date=get('journal-date').value,before=Object.fromEntries(P.ASSETS.map(a=>[a,read(a)])),deposit=read('journal-deposit'),orders=['QQQ','GOLD','BTC'].map(a=>({asset:a,buyAmount:read('journal-buy-'+a),sellAmount:read('journal-sell-'+a)})),reason=get('journal-reason').value,memo=get('journal-memo').value;
   const signature=JSON.stringify({date,before,deposit,orders,reason,memo});
   const snapshot=date===today?await AllocationData.get().getLatestSnapshot():await AllocationData.get().getSnapshot(date);
   const nowSignature=JSON.stringify({date:get('journal-date').value,before:Object.fromEntries(P.ASSETS.map(a=>[a,read(a)])),deposit:read('journal-deposit'),orders:['QQQ','GOLD','BTC'].map(a=>({asset:a,buyAmount:read('journal-buy-'+a),sellAmount:read('journal-sell-'+a)})),reason:get('journal-reason').value,memo:get('journal-memo').value});
   if(signature!==nowSignature)throw Error('조회 중 입력이 변경되었습니다. 다시 미리보기하세요.');
   draft=J.create({date,before,deposit,orders,reason,memo,snapshot},today);
   get('journal-preview').innerHTML=`<p>입금 ${money(deposit)} · 거래 후 합계 ${money(P.value(draft.portfolioAfter))}</p>${P.ASSETS.map(a=>`<p>${labels[a]} ${money(before[a])} → ${money(draft.portfolioAfter[a])}</p>`).join('')}<p>${snapshot?'표시된 시점의 Score와 모델을 고정합니다.':'당시 Score·모델을 확보하지 못했습니다. 미확보 상태로 기록합니다.'} 가격이 없으면 수익률은 대기합니다.</p>`;get('journal-confirm').hidden=false;status('내용 확인 후 저장하세요.');
 }catch(e){status(e.message);}finally{locked=false;}};
 get('journal-confirm').onclick=async()=>{if(locked||!draft)return;locked=true;get('journal-confirm').disabled=true;try{await AllocationStore.add('journals',draft);draft=null;get('journal-confirm').hidden=true;status('매매일지를 브라우저에 저장했습니다.');await list();}catch(e){status(e.message);}finally{locked=false;get('journal-confirm').disabled=false;}};
 try{await list();}catch(e){status('일지 저장소를 사용할 수 없습니다: '+e.message);}
})();
