(function(root){
 const host=document.getElementById('score-trends');if(!host)return;
 const names={QQQ:'QQQ · 주식',BTC:'Bitcoin',GOLD:'Gold · 금',CASH:'Cash · 현금'},colors={QQQ:'#3264e8',BTC:'#e59932',GOLD:'#9b883f',CASH:'#758b9c'};
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const factorNames={equity_trend:'나스닥100 추세',relative_equity:'나스닥100/S&P500 상대강도',btc_trend:'비트코인 추세',gold_trend:'금 추세',btc_gold:'BTC/Gold',dollar:'달러인덱스',nominal_yield:'명목 10년 금리',liquidity:'연준 자산'};
 const number=n=>Number.isFinite(n)?n.toFixed(4):'—';
 let previous='';
 function formula(a,state){
   const score=state.result?.scores?.[a];if(!score)return '<p>계산 상세 자료가 없습니다.</p>';
   const terms=score.contributions||[],sum=terms.reduce((n,c)=>n+c.points,0);
   return `<details data-keep="formula-${a}"><summary>Score 계산식 · 현재 적용값</summary><p>기준일 ${esc(state.result.market_date)} · 현재 Score <strong>${number(score.current_score)}</strong> · 데이터 충족률 ${number(score.data_coverage*100)}%</p><p><code>Score = 50 + Σ(50 × 현재 가중치 × 방향 적용 정규화값)</code></p><p>현재 계산: 50 + (${number(sum)}) = <strong>${number(50+sum)}</strong></p><p>정규화값 = clip((변환값 − 과거 평균) / 과거 표준편차 / 3, −1, 1). 평균·표준편차에서 현재 관측은 제외합니다. 가격·비율은 로그 변화, 명목 금리는 차이를 사용합니다. 방향 적용값은 자산별 유불리 부호를 곱한 값입니다.</p><div class="table-wrap"><table><tr><th>요인</th><th>현재 가중치</th><th>방향 적용값*</th><th>산출식</th><th>기여점수</th><th>상태</th></tr>${terms.map(c=>`<tr><th>${esc(factorNames[c.factor]||c.factor)}</th><td>${number(c.weight*100)}%</td><td>${c.data_status==='ok'&&c.weight>0?number(c.points/(50*c.weight)):'—'}</td><td>50 × ${number(c.weight)} × ${c.data_status==='ok'&&c.weight>0?number(c.points/(50*c.weight)):'0 (미반영)'}</td><td>${number(c.points)}</td><td>${esc(c.data_status)}</td></tr>`).join('')}</table></div><p class="small">* 방향 적용값은 공개된 기여점수 ÷ (50 × 가중치)로 복원했습니다. 원본 지표 현재값·과거 평균·표준편차는 공개 데이터에 없어 표시하지 않습니다. 결측 요인은 기여 0으로 처리하며 다른 요인 가중치를 재정규화하지 않습니다. 표시는 반올림하여 작은 합계 차이가 있을 수 있습니다.</p><p class="small">모델 ${esc(state.normalizedSnapshot?.modelVersion||state.result.config_hash||'미제공')} · 계산 상세는 위 기준일의 값이며 과거 점의 계산식 상세는 저장되어 있지 않습니다.</p></details>`;
 }
 async function draw(){try{
   const [all,state]=await Promise.all([AllocationData.get().getScoreHistory(),AllocationData.get().getDashboardState()]);const latest=state.normalizedSnapshot;
   const rows=all.filter(r=>r.modelVersion===latest?.modelVersion&&Date.parse(r.availableAt)<=Date.now()).sort((a,b)=>a.date.localeCompare(b.date));
   const fingerprint=JSON.stringify([rows,state.result]);if(fingerprint===previous)return;previous=fingerprint;
   const opened=[...host.querySelectorAll('details[open][data-keep]')].map(e=>e.dataset.keep);
   host.innerHTML='<h2>자산별 Score 추이</h2><p class="muted">실제로 기록된 같은 모델의 Score만 표시합니다. 빈 날짜는 새로 계산하지 않습니다. 세로축 0~100.</p><div class="trend-grid">'+Object.keys(names).map(a=>{
     const points=rows.filter(r=>Number.isFinite(r.scores[a]));if(!points.length)return `<article><h3>${names[a]}</h3><p>기록이 아직 없습니다.</p></article>`;
     const first=Date.parse(points[0].date),last=Date.parse(points.at(-1).date),x=r=>35+(Date.parse(r.date)-first)/(last-first||1)*280,y=r=>125-r.scores[a];
     return `<article><h3>${names[a]}</h3><svg viewBox="0 0 350 160" role="img" aria-label="${names[a]} 환경 Score 추이"><text x="0" y="28">100</text><text x="14" y="128">0</text><path d="M30 25V125H325" fill="none" stroke="#cdd8e4"/><polyline points="${points.map(r=>`${x(r)},${y(r)}`).join(' ')}" fill="none" stroke="${colors[a]}" stroke-width="2"/>${points.map(r=>`<circle tabindex="0" role="button" data-score-asset="${a}" data-score-date="${r.date}" data-score-value="${r.scores[a].toFixed(2)}" aria-label="${r.date} ${names[a]} Score ${r.scores[a].toFixed(2)}" cx="${x(r)}" cy="${y(r)}" r="5" fill="${colors[a]}"><title>${r.date}: ${r.scores[a].toFixed(2)}</title></circle>`).join('')}<text x="30" y="150">${points[0].date}</text><text x="240" y="150">${points.at(-1).date}</text></svg><p id="score-point-${a}" aria-live="polite">${points.at(-1).date} · Score ${points.at(-1).scores[a].toFixed(2)}점</p><p class="small">점을 누르거나 마우스를 올리면 날짜와 Score가 표시됩니다.</p><details data-keep="dates-${a}"><summary>날짜별 Score (${points.length}개)</summary><div class="table-wrap"><table><tr><th>날짜</th><th>Score</th></tr>${points.map(r=>`<tr><td>${r.date}</td><td>${r.scores[a].toFixed(2)}</td></tr>`).join('')}</table></div></details>${formula(a,state)}</article>`;
   }).join('')+'</div><details><summary>날짜별 Score 값 보기</summary><div class="table-wrap"><table><tr><th>기준일</th>'+Object.values(names).map(n=>`<th>${n}</th>`).join('')+'</tr>'+rows.map(r=>`<tr><td>${r.date}</td>${Object.keys(names).map(a=>`<td>${r.scores[a]===null?'—':r.scores[a].toFixed(2)}</td>`).join('')}</tr>`).join('')+'</table></div></details><p class="small">모델 '+esc(latest?.modelVersion?.slice(0,12)||'미확보')+' · 모델이 바뀌면 다른 버전의 선을 연결하지 않습니다.</p>';
   for(const d of host.querySelectorAll('details[data-keep]'))d.open=opened.includes(d.dataset.keep);
   host.querySelectorAll('[data-score-asset]').forEach(dot=>{const show=()=>{document.getElementById('score-point-'+dot.dataset.scoreAsset).textContent=dot.dataset.scoreDate+' · Score '+dot.dataset.scoreValue+'점';};['mouseenter','focus','click'].forEach(event=>dot.addEventListener(event,show));dot.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}});});
 }catch(e){host.textContent='Score 추이를 불러오지 못했습니다: '+e.message;}}
 draw();setInterval(draw,30000);
})(globalThis);
