(async function(){
 const host=document.getElementById('simulation-section');if(!host)return;
 const E=SimulationEngine,P=PortfolioEngine,names={QQQ:'주식',GOLD:'금',BTC:'비트코인',CASH:'현금·단기채'},fmt=(n,usd)=>AllocationCurrency.money(n,session?.window[session.cursor]?.fx?.value??null,usd);
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let rows=[],session=null,previewed=null,locked=false,available=false;
 host.innerHTML=`<h2>과거에서 판단 연습</h2><p class="muted">초기자산은 투자현황 탭의 현재 평가액을 사용합니다. 시작 월은 데이터가 모두 있는 구간에서 무작위로 선택합니다.</p><p id="sim-status" role="status">데이터 확인 중…</p><label>기간 <select id="sim-years"><option value="1">1년</option><option value="3">3년</option><option value="5">5년</option><option value="10">10년</option></select></label> <label>매월 새로 적립할 금액 (원) <input id="sim-monthly" type="number" min="0" max="1000000000000000" step="1" placeholder="반복 월납입금"></label><button id="sim-start" class="secondary" disabled>새 연습 시작</button><div id="sim-sessions"></div><div id="sim-body"></div>`;
 const get=id=>document.getElementById(id),status=text=>get('sim-status').textContent=text;
 async function list(){const all=await AllocationStore.list('sessions');get('sim-sessions').innerHTML=all.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(s=>`<button class="secondary" data-session="${esc(s.id)}">${esc(s.startDate)} · ${s.duration}년 · ${s.cursor}/${s.duration*12}개월 이어보기</button>`).join('');get('sim-sessions').querySelectorAll('button').forEach(b=>b.onclick=()=>perform(async()=>{session=await AllocationStore.get('sessions',b.dataset.session);draw();}));}
 async function perform(fn){if(locked)return;locked=true;host.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message);}finally{locked=false;host.querySelectorAll('button').forEach(b=>b.disabled=false);get('sim-start').disabled=!available;}}
 function draw(){previewed=null;const v=E.view(session),last=session.decisions.at(-1);get('sim-body').innerHTML=`<h3>${esc(v.date)} · ${session.cursor}/${session.duration*12}개월</h3><p>${v.fx?`당시 환율: 1 USD = ${v.fx.value.toFixed(2)}원 (${v.fx.sourceDate}) · 월말 관측 후 다음 월 구간 평가`:"당시 환율 미확보: 달러 환산 불가"}</p><p>현재 총자산 <strong>${fmt(P.value(v.portfolio))}</strong> · 누적 납입원금 ${fmt(v.principal,v.principalUSD)} · 손익 ${fmt(P.value(v.portfolio)-v.principal,v.fx&&v.principalUSD!==null?P.value(v.portfolio)/v.fx.value-v.principalUSD:undefined)}</p>${last?`<p>직전 월 원화 포트폴리오 수익률 ${(last.periodReturn*100).toFixed(2)}% (월초 납입금 반영 후 기준)${last.periodReturnUSD!=null?` · 달러 ${(last.periodReturnUSD*100).toFixed(2)}%`:""}</p>`:''}<div class="table-wrap"><table><thead><tr><th>자산</th><th>평가액</th><th>비중</th><th>당시 Score</th><th>관측가격 (원화)</th></tr></thead><tbody>${P.ASSETS.map(a=>`<tr><th>${names[a]}</th><td>${fmt(v.portfolio[a])}</td><td>${(P.allocation(v.portfolio)[a]*100).toFixed(1)}%</td><td>${v.scores[a]??'과거 Score 없음'}</td><td>${v.prices[a].toFixed(2)}</td></tr>`).join('')}</tbody></table></div><label>과거 그래프 <select id="sim-lookback"><option value="1">1개월</option><option value="6">6개월</option><option value="12" selected>1년</option></select></label><div id="sim-chart"></div><div id="sim-benchmarks"></div><div id="sim-performance"></div>${v.completed?'<h3>연습을 마쳤습니다.</h3><p>이제 현재입니다. 위의 최신 Score를 확인하고 지금의 판단을 생각해 보세요. 위의 최종 성과 보고서에서 납입원금과 투자손익을 구분해 확인하세요.</p>':`<p>이번 달 신규자금 ${fmt(v.monthlyContribution)} · 모든 매도 후 매수를 처리합니다.</p><form id="sim-form"><div class="table-wrap"><table><thead><tr><th>자산</th><th>매수 원</th><th>매도 원</th><th>또는 매도 %</th></tr></thead><tbody>${['QQQ','GOLD','BTC'].map(a=>`<tr><th>${names[a]}</th>${['buy','sell','percent'].map(k=>`<td><input id="sim-${k}-${a}" aria-label="${names[a]} ${k}" type="number" value="0" min="0" max="${k==='percent'?100:1e15}" step="${k==='percent'?.1:1}" required></td>`).join('')}</tr>`).join('')}</tbody></table></div><label>그때 왜 그렇게 했나요? <select id="sim-reason" required><option value="">이유 선택</option>${E.REASONS.map(r=>`<option>${r}</option>`).join('')}</select></label><label>메모 <textarea id="sim-memo" maxlength="4000"></textarea></label><button class="secondary" type="submit">변경 전후 확인</button><div id="sim-preview"></div><button class="primary" id="sim-confirm" type="button" hidden>이유와 판단 저장 후 다음 달로</button></form>`}<details><summary>내 판단 기록 (${session.decisions.length}건)</summary>${session.decisions.map(d=>`<p>${esc(d.decisionDate)} · ${esc(d.reasonCategory)}<br>${esc(d.reasonMemo)}</p>`).join('')}</details>`;
   renderBenchmark(session,get('sim-benchmarks'));renderPerformance(session,get('sim-performance'));chart();get('sim-lookback').onchange=chart;if(v.completed)return;
   const form=get('sim-form');form.oninput=()=>{previewed=null;get('sim-confirm').hidden=true;get('sim-preview').textContent='입력 변경 후 다시 확인해 주세요.';};
   form.onsubmit=event=>{event.preventDefault();try{const orders=['QQQ','GOLD','BTC'].map(a=>({asset:a,buyAmount:Number(get('sim-buy-'+a).value),sellAmount:Number(get('sim-sell-'+a).value),sellPercent:Number(get('sim-percent-'+a).value)}));const p=P.preview(v.portfolio,v.monthlyContribution,orders);const reason=get('sim-reason').value,memo=get('sim-memo').value;if(!reason||(reason==='기타'&&!memo.trim()))throw Error('판단 이유를 기록하세요. 기타는 메모가 필요합니다.');previewed={orders,reason,memo};get('sim-preview').innerHTML=P.ASSETS.map(a=>`<p>${names[a]}: ${(p.weightsBefore[a]*100).toFixed(1)}% → ${(p.weightsAfter[a]*100).toFixed(1)}% · ${fmt(p.after[a])}</p>`).join('')+p.notes.map(n=>`<p>${esc(n)}</p>`).join('');get('sim-confirm').hidden=false;}catch(e){status(e.message);}};
   get('sim-confirm').onclick=()=>perform(async()=>{if(!previewed)throw Error('먼저 변경 내용을 확인하세요.');const next=E.decide(session,previewed.orders,previewed.reason,previewed.memo);await AllocationStore.commitSimulation(next.session,next.decision);session=next.session;status('판단과 당시 Snapshot을 저장했습니다. 다음 월 결과입니다.');draw();await list();});
 }
 function chart(){const h=E.view(session).history.slice(-Number(get('sim-lookback').value)-1);if(h.length<2){get('sim-chart').textContent='시작 월 이전 그래프 데이터가 없습니다.';return;}const colors=['#3264e8','#9b883f','#e59932','#758b9c'],values=P.ASSETS.map(a=>h.map(s=>(s.prices[a]/(AllocationCurrency.mode==='USD'?(s.fx?.value||1):1))/(h[0].prices[a]/(AllocationCurrency.mode==='USD'?(h[0].fx?.value||1):1))*100)),all=values.flat(),lo=Math.min(...all),hi=Math.max(...all),y=v=>160-(v-lo)/(hi-lo||1)*130;get('sim-chart').innerHTML=`<svg viewBox="0 0 600 190" role="img" aria-label="현재 월까지의 자산별 상대가격 그래프">${values.map((line,i)=>`<polyline fill="none" stroke="${colors[i]}" stroke-width="2" points="${line.map((v,j)=>`${20+j/(h.length-1)*560},${y(v)}`).join(' ')}"/>`).join('')}<text x="20" y="185" font-size="12">${esc(h[0].date)}</text><text x="470" y="185" font-size="12">${esc(h.at(-1).date)}</text></svg><p>${P.ASSETS.map((a,i)=>`<span style="color:${colors[i]}">${names[a]}</span>`).join(' · ')} · ${AllocationCurrency.mode} 기준 · 구간 시작=100 · 월별 관측</p>`;}
 window.addEventListener('currencychange',()=>{if(session){chart();renderPerformance(session,get('sim-performance'));}});
 get('sim-start').onclick=()=>perform(async()=>{const input=Object.fromEntries(P.ASSETS.map(a=>{const e=document.getElementById(a);if(!e.value.trim())throw Error('위의 현재 보유액을 모두 입력하세요.');return [a,Number(e.value)];}));if(!get('sim-monthly').value.trim())throw Error('반복 월납입금을 입력하세요.');const s=E.start(rows,Number(get('sim-years').value),input,Number(get('sim-monthly').value));await AllocationStore.add('sessions',s);session=s;draw();await list();status('시작 월을 무작위로 선택했습니다.');});
 try{const range=await AllocationHistory.get().getAvailableDateRange();if(range.errors?.historical)throw Error(range.errors.historical);rows=range.rows;for(const option of get('sim-years').options)option.disabled=!range.periods[option.value];const first=[...get('sim-years').options].find(o=>!o.disabled);if(first)get('sim-years').value=first.value;available=!!first;get('sim-start').disabled=!first;status((rows.length?'월별 가격 '+rows.length+'개월 ('+rows[0].date+' ~ '+rows[rows.length-1].date+') 연결됨. ':'')+(first?'가격·당시 환율을 사용하는 체험입니다. 주식=SPY, 현금·단기채=BIL입니다. 과거 Score/개발자 전략은 미확보이며, 월말 가격으로 거래한다고 가정합니다.':'연습 데이터 준비 중: 1년 이상 연속된 원화 가격·당시 Score 이력이 없어 시작할 수 없습니다. 과거 Score를 임의 생성하지 않으며, 가격만 사용하는 체험은 준비 중입니다.'));}catch(e){status(e.message);}try{await list();}catch(e){status('기록 저장소를 열 수 없습니다: '+e.message);}
})();
